spring:
  datasource:
    url: jdbc:mysql://localhost:3306/querydsl
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # DB ??? ??
    properties:
      hibernate:
        format_sql: true // SQL??? ??? ??
#          show_sql: true // ???? SQL??? System.out.println ?? ???. org.hibernate.SQL ?? ??? ????? ???? ? ??

logging:
  level:
    org.hibernate.SQL: debug // # ?????? SQL ??? ??? ??? ?. ??? ??? ??(???? "SQL"? ???? ???)
    # org.hibernate.orm.jdbc.bind: trace // ?? ???, ???? ??? ?? ??? ? ??. ???3 ??????? org.hibernate.type: trace ? ?? ?